In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

In [3]:
arr = np.array([1, 2, 2, 3, 4, 5])
arr2d = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]])
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])


In [4]:
print(arr[0])  # 1D array
print(arr2d[0, 1])  # 2D array
print(arr3d[0, 1, 2])  # 3D array


1
2
6


In [5]:
print(arr.ndim)  # Number of dimensions
print(arr.shape)  # Shape of the array
print(arr.size)  # Total number of elements
print(arr.dtype)  # Data type of elements


1
(6,)
6
int32


In [6]:
print(arr2d.ndim)  # Number of dimensions
print(arr2d.shape)  # Shape of the array
print(arr2d.size)  # Total number of elements
print(arr2d.dtype)  # Data type of elements

2
(2, 6)
12
int32


In [7]:
print(arr3d.ndim)  # Number of dimensions
print(arr3d.shape)  # Shape of the array
print(arr3d.size)  # Total number of elements
print(arr3d.dtype)  # Data type of elements

3
(2, 2, 3)
12
int32


In [8]:
print(arr[0:3])  # Slicing 1D array
print(arr2d[:, 1:3])  # Slicing 2D array
print(arr3d[:, :, 1])  # Slicing 3D array


[1 2 2]
[[2 3]
 [8 9]]
[[ 2  5]
 [ 8 11]]


In [9]:
a8 = np.array([1.1, 2.1, 3.1])
new_a8 = a8.astype(int)  # Convert float to int
print(new_a8)


[1 2 3]


In [10]:
zero_arr = np.zeros((2, 2))
one_arr = np.ones((2, 2))
full_arr = np.full((2, 2), 5)
eye_arr = np.eye(3)  # Identity matrix


In [11]:
vector_1 = np.array([2, 4, 6, 8, 10])
vector_2 = np.array([12, 16, 18, 24, 20])

print(vector_1 + vector_2)  # Addition
print(vector_1 - vector_2)  # Subtraction
print(vector_1 * vector_2)  # Multiplication
print(vector_2 / vector_1)  # Division
print(vector_1.dot(vector_2))  # Dot product


[14 20 24 32 30]
[-10 -12 -12 -16 -10]
[ 24  64 108 192 200]
[6. 4. 3. 3. 2.]
588


In [13]:
a = np.arange(10).reshape(2, 5)
print(a.max())  # Maximum value
print(a.min())  # Minimum value
print(np.argmax(a))  # Index of max value
print(np.argmin(a))  # Index of min value

# Creating arrays with specific patterns
arrange_arr = np.arange(10)
linspace_arr = np.linspace(0, 9, 5)


9
0
9
0
